# Generated by Django 5.2.17 on 2026-09-24 21:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=250)),
                ('isbn', models.CharField(blank=True, max_length=50)),
                ('edition', models.CharField(blank=True, max_length=80)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('lcc_class', models.CharField(help_text='Example: Z', max_length=10)),
                ('lcc_number', models.CharField(help_text='Example: 665', max_length=30)),
                ('cutter_number', models.CharField(blank=True, help_text='Example: .L53', max_length=30)),
                ('call_number', models.CharField(db_index=True, max_length=100)),
                ('collection', models.CharField(default='Reserve', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('level', models.CharField(blank=True, max_length=30)),
                ('semester', models.CharField(blank=True, max_length=30)),
                ('session', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_no', models.CharField(max_length=80, unique=True)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('copy_no', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(default='Good', max_length=50)),
                ('status', models.CharField(default='Available', max_length=30)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='core.book')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('material_type', models.CharField(default='PDF', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='digital_reserve/')),
                ('external_url', models.URLField(blank=True)),
                ('access_level', models.CharField(choices=[('Course', 'Course students'), ('All Students', 'All students'), ('Staff', 'Staff only')], default='Course', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digital_materials', to='core.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lecturer'),
        ),
        migrations.CreateModel(
            name='ReserveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_copies', models.PositiveIntegerField(default=1)),
                ('reserve_type', models.CharField(default='Core', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_no', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('programme', models.CharField(blank=True, max_length=150)),
                ('level', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(default='General', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_time', models.DateTimeField()),
                ('returned_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='On Loan', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bookcopy')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_transactions', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_transactions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ready', 'Ready'), ('Fulfilled', 'Fulfilled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.student')),
            ],
            options={
                'ordering': ['requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['Pending', 'Ready'])), fields=('student', 'book'), name='unique_active_student_book_reservation')],
            },
        ),
    ]
